name: rionegro_marca_ciudad
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  animated_splash_screen: ^1.3.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_polyline_points: ^2.0.0
  flutter_riverpod: ^2.4.6
  geolocator: ^10.1.0
  go_router: ^12.1.1
  google_maps_flutter: ^2.5.0
  supabase_flutter: ^1.10.25

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/rutas/

  fonts:
    - family: Gotham
      fonts:
        - asset: assets/fonts/Gotham-Book.otf
        - asset: assets/fonts/Gotham-Light.otf
        - asset: assets/fonts/Gotham-Medium.otf
        - asset: assets/fonts/Gotham-Bold.otf
          weight: 800
